include_guard(GLOBAL)

if(NOT DEFINED QUILT_TEST_BINARY_DIR OR QUILT_TEST_BINARY_DIR STREQUAL "")
    message(FATAL_ERROR "QUILT_TEST_BINARY_DIR is required")
endif()

if(NOT DEFINED QUILT_TEST_EXECUTABLE OR QUILT_TEST_EXECUTABLE STREQUAL "")
    message(FATAL_ERROR "QUILT_TEST_EXECUTABLE is required")
endif()

set(QT_TEST_ROOT "${QUILT_TEST_BINARY_DIR}/test-work")
file(MAKE_DIRECTORY "${QT_TEST_ROOT}")

function(qt_fail message_text)
    message(FATAL_ERROR "${message_text}")
endfunction()

function(qt_begin_test scenario)
    string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef suffix)
    set(work_dir "${QT_TEST_ROOT}/${scenario}-${suffix}")
    file(MAKE_DIRECTORY "${work_dir}")
    set_property(GLOBAL PROPERTY QT_TEST_BASE "${work_dir}")
    set_property(GLOBAL PROPERTY QT_WORK_DIR "${work_dir}")
    set(QT_TEST_BASE "${work_dir}" PARENT_SCOPE)
    set(QT_WORK_DIR "${work_dir}" PARENT_SCOPE)
endfunction()

function(qt_write_file path content)
    get_filename_component(parent_dir "${path}" DIRECTORY)
    if(NOT parent_dir STREQUAL "")
        file(MAKE_DIRECTORY "${parent_dir}")
    endif()
    file(WRITE "${path}" "${content}")
endfunction()

function(qt_append_file path content)
    get_filename_component(parent_dir "${path}" DIRECTORY)
    if(NOT parent_dir STREQUAL "")
        file(MAKE_DIRECTORY "${parent_dir}")
    endif()
    file(APPEND "${path}" "${content}")
endfunction()

function(qt_read_file_strip out_var path)
    if(NOT EXISTS "${path}")
        qt_fail("Missing file: ${path}")
    endif()
    file(READ "${path}" content)
    string(REGEX REPLACE "\r\n" "\n" content "${content}")
    string(REGEX REPLACE "\n+$" "" content "${content}")
    set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

function(qt_read_file_raw out_var path)
    if(NOT EXISTS "${path}")
        qt_fail("Missing file: ${path}")
    endif()
    file(READ "${path}" content)
    string(REGEX REPLACE "\r\n" "\n" content "${content}")
    set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

function(qt_assert_exists path message_text)
    if(NOT EXISTS "${path}")
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_not_exists path message_text)
    if(EXISTS "${path}")
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_dir_exists path message_text)
    if(NOT IS_DIRECTORY "${path}")
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_equal actual expected message_text)
    if(NOT "${actual}" STREQUAL "${expected}")
        qt_fail("${message_text} (expected: ${expected}, got: ${actual})")
    endif()
endfunction()

function(qt_assert_success rc message_text)
    if(NOT "${rc}" STREQUAL "0")
        qt_fail("${message_text} (exit ${rc})")
    endif()
endfunction()

function(qt_assert_failure rc message_text)
    if("${rc}" STREQUAL "0")
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_not_equal actual unexpected message_text)
    if("${actual}" STREQUAL "${unexpected}")
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_contains text needle message_text)
    string(FIND "${text}" "${needle}" match_pos)
    if(match_pos EQUAL -1)
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_not_contains text needle message_text)
    string(FIND "${text}" "${needle}" match_pos)
    if(NOT match_pos EQUAL -1)
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_matches text regex message_text)
    if(NOT "${text}" MATCHES "${regex}")
        qt_fail("${message_text}")
    endif()
endfunction()

function(qt_assert_file_text path expected message_text)
    qt_read_file_strip(actual "${path}")
    qt_assert_equal("${actual}" "${expected}" "${message_text}")
endfunction()

function(qt_assert_file_contains path needle message_text)
    qt_read_file_raw(content "${path}")
    qt_assert_contains("${content}" "${needle}" "${message_text}")
endfunction()

function(qt_assert_file_not_contains path needle message_text)
    qt_read_file_raw(content "${path}")
    qt_assert_not_contains("${content}" "${needle}" "${message_text}")
endfunction()

function(qt_count_lines out_var text)
    string(REGEX REPLACE "\r\n" "\n" normalized "${text}")
    if(normalized STREQUAL "")
        set(count 0)
    else()
        string(REGEX MATCHALL "\n" newline_matches "${normalized}")
        list(LENGTH newline_matches count)
        if(NOT normalized MATCHES "\n$")
            math(EXPR count "${count} + 1")
        endif()
    endif()
    set(${out_var} "${count}" PARENT_SCOPE)
endfunction()

function(qt_assert_line_count text expected message_text)
    qt_count_lines(actual_count "${text}")
    if(NOT "${actual_count}" STREQUAL "${expected}")
        qt_fail("${message_text} (expected: ${expected}, got: ${actual_count})")
    endif()
endfunction()

function(qt_combine_output out_var stdout_text stderr_text)
    set(${out_var} "${stdout_text}${stderr_text}" PARENT_SCOPE)
endfunction()

function(qt_quilt)
    set(options)
    set(one_value_args RESULT OUTPUT ERROR WORKING_DIRECTORY INPUT)
    set(multi_value_args ARGS ENV)
    cmake_parse_arguments(QT "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(NOT DEFINED QT_RESULT OR QT_RESULT STREQUAL "")
        qt_fail("qt_quilt requires RESULT")
    endif()
    if(NOT DEFINED QT_OUTPUT OR QT_OUTPUT STREQUAL "")
        qt_fail("qt_quilt requires OUTPUT")
    endif()
    if(NOT DEFINED QT_ERROR OR QT_ERROR STREQUAL "")
        qt_fail("qt_quilt requires ERROR")
    endif()

    if(DEFINED QT_WORKING_DIRECTORY AND NOT QT_WORKING_DIRECTORY STREQUAL "")
        set(work_dir "${QT_WORKING_DIRECTORY}")
    else()
        get_property(work_dir GLOBAL PROPERTY QT_WORK_DIR)
    endif()
    if(NOT DEFINED work_dir OR work_dir STREQUAL "")
        qt_fail("qt_quilt requires a working directory")
    endif()

    if(DEFINED QT_ENV AND NOT QT_ENV STREQUAL "")
        set(command "${CMAKE_COMMAND}" "-E" "env")
        foreach(env_entry IN LISTS QT_ENV)
            list(APPEND command "${env_entry}")
        endforeach()
        list(APPEND command "${QUILT_TEST_EXECUTABLE}")
    else()
        set(command "${QUILT_TEST_EXECUTABLE}")
    endif()
    list(APPEND command ${QT_ARGS})
    set(wrapped_command "${CMAKE_COMMAND}" "-E" "chdir" "${work_dir}")
    list(APPEND wrapped_command ${command})

    set(input_file)
    if(DEFINED QT_INPUT AND NOT QT_INPUT STREQUAL "")
        string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef input_suffix)
        get_property(test_base GLOBAL PROPERTY QT_TEST_BASE)
        if(NOT DEFINED test_base OR test_base STREQUAL "")
            qt_fail("qt_quilt requires QT_TEST_BASE when using INPUT")
        endif()
        set(input_file "${test_base}/input-${input_suffix}.txt")
        file(WRITE "${input_file}" "${QT_INPUT}")
        execute_process(
            COMMAND ${wrapped_command}
            RESULT_VARIABLE result
            OUTPUT_VARIABLE output
            ERROR_VARIABLE error
            INPUT_FILE "${input_file}"
        )
    else()
        execute_process(
            COMMAND ${wrapped_command}
            RESULT_VARIABLE result
            OUTPUT_VARIABLE output
            ERROR_VARIABLE error
        )
    endif()

    string(REGEX REPLACE "\r\n" "\n" output "${output}")
    string(REGEX REPLACE "\r\n" "\n" error "${error}")
    set(${QT_RESULT} "${result}" PARENT_SCOPE)
    set(${QT_OUTPUT} "${output}" PARENT_SCOPE)
    set(${QT_ERROR} "${error}" PARENT_SCOPE)
endfunction()

function(qt_quilt_ok)
    set(options)
    set(one_value_args OUTPUT ERROR WORKING_DIRECTORY INPUT MESSAGE)
    set(multi_value_args ARGS ENV)
    cmake_parse_arguments(QTO "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    set(call_args
        RESULT result
        OUTPUT output
        ERROR error
    )
    if(DEFINED QTO_WORKING_DIRECTORY AND NOT QTO_WORKING_DIRECTORY STREQUAL "")
        list(APPEND call_args WORKING_DIRECTORY "${QTO_WORKING_DIRECTORY}")
    endif()
    if(DEFINED QTO_INPUT AND NOT QTO_INPUT STREQUAL "")
        list(APPEND call_args INPUT "${QTO_INPUT}")
    endif()
    if(DEFINED QTO_ENV AND NOT QTO_ENV STREQUAL "")
        list(APPEND call_args ENV ${QTO_ENV})
    endif()
    list(APPEND call_args ARGS ${QTO_ARGS})

    qt_quilt(${call_args})
    if(NOT "${result}" STREQUAL "0")
        qt_combine_output(combined "${output}" "${error}")
        if(DEFINED QTO_MESSAGE AND NOT QTO_MESSAGE STREQUAL "")
            qt_fail("${QTO_MESSAGE} (exit ${result}): ${combined}")
        else()
            qt_fail("quilt command failed (exit ${result}): ${combined}")
        endif()
    endif()

    if(DEFINED QTO_OUTPUT AND NOT QTO_OUTPUT STREQUAL "")
        set(${QTO_OUTPUT} "${output}" PARENT_SCOPE)
    endif()
    if(DEFINED QTO_ERROR AND NOT QTO_ERROR STREQUAL "")
        set(${QTO_ERROR} "${error}" PARENT_SCOPE)
    endif()
endfunction()
