#!/usr/bin/env python3
"""
cmake/make_amalgam.py
Generates quilt.cpp: a single-file amalgamation of all sources (Windows platform).

Usage: python3 make_amalgam.py <source-root> <output-path>
"""

import sys
import os
import re

SOURCES = [
    "src/quilt.hpp",
    "src/platform.hpp",
    "src/core.cpp",
    "src/cmd_stack.cpp",
    "src/cmd_patch.cpp",
    "src/cmd_manage.cpp",
    "src/cmd_stubs.cpp",
    "src/platform_win32.cpp",
]

LOCAL_INCLUDES = re.compile(r'^\s*#include\s+"(quilt\.hpp|platform\.hpp)"\s*$')
PRAGMA_ONCE    = re.compile(r'^\s*#pragma\s+once\s*$')
STATIC_FUNC    = re.compile(r'^static\s+\S.*\s(\w+)\s*\(')


def skip_function_body(lines, start):
    """Return the index past the closing brace of a function starting at start."""
    depth = 0
    found_open = False
    i = start
    while i < len(lines):
        for ch in lines[i]:
            if ch == '{':
                depth += 1
                found_open = True
            elif ch == '}':
                depth -= 1
        i += 1
        if found_open and depth == 0:
            break
    return i


def process_file(path, seen_statics):
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    out = []
    i = 0
    while i < len(lines):
        line = lines[i]

        # Strip pragma once and local includes
        if PRAGMA_ONCE.match(line) or LOCAL_INCLUDES.match(line):
            i += 1
            continue

        # Detect static function definitions; skip if already seen
        m = STATIC_FUNC.match(line)
        if m:
            name = m.group(1)
            if name in seen_statics:
                # Skip entire function body
                i = skip_function_body(lines, i)
                continue
            seen_statics.add(name)

        out.append(line)
        i += 1

    return out


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <source-root> <output>", file=sys.stderr)
        sys.exit(1)

    source_root = sys.argv[1]
    output_path = sys.argv[2]

    seen_statics = set()
    chunks = []
    chunks.append(
        "// quilt.cpp — single-file amalgamation (Windows platform)\n"
        "// Generated by cmake/make_amalgam.py — do not edit directly\n\n"
    )

    for src in SOURCES:
        path = os.path.join(source_root, src)
        chunks.append(f"// === {src} ===\n\n")
        lines = process_file(path, seen_statics)
        chunks.append("".join(lines))
        chunks.append("\n")

    with open(output_path, "w", encoding="utf-8") as f:
        f.writelines(chunks)

    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
